name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
  followers:
   runs-on: ubuntu-latest
   permissions:
      contents: write
   steps:
      - uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.people.followers.svg
         token: ${{ secrets.FOLLOWER_KEY }}
         base: ""
         plugin_people: yes
         plugin_people_types: followers
         
         
 gith:
  runs-on: ubuntu-latest
   permissions:
      contents: write
   steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_compatibility: no
